# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    
    # General Vagrant VM configuration
    config.vm.box = "geerlingguy/centos7"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider :virtualbox do |v|
        v.memory = 256
        v.linked_clone = true
    end

    # Application server 1.
    config.vm.define "nodejs" do |app|
        app.vm.hostname = "nodejs.test"
        app.vm.network :private_network, ip: "192.168.60.4"
    end

end
